apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "entitle-agent.fullname" . }}-deployment
  labels:
  {{- include "entitle-agent.labels" . | nindent 4 }}
rules:
  - verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
    apiGroups: ["apps"]
    resources:
      - deployments
  - verbs:
      - get
      - list
      - watch
    apiGroups: [ "" ]
    resources:
      - pods
  - verbs:
      - get
      - list
      - watch
    apiGroups: [ "apps" ]
    resources:
      - replicasets
  - verbs:
      - get
    apiGroups:
      - ""
    resources:
      - serviceaccounts
    resourceNames:
      - {{ include "entitle-agent.serviceAccountName" . }}
  - verbs:
      - '*'
    apiGroups:
      - '*'
    resources:
      - jobs
  - verbs:
      - '*'
    apiGroups:
      - '*'
    resources:
      - secrets
