{{- if .Values.agent.token }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "entitle-agent.fullname" . }}-secret
  labels:
  {{- include "entitle-agent.labels" . | nindent 4 }}
stringData:
  ENTITLE_JSON_CONFIGURATION: "{\"BASE64_CONFIGURATION\":\"{{ .Values.agent.token }}\"}"
{{- end }}
