apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "entitle-agent.serviceAccountName" . }}
  labels:
    {{- include "entitle-agent.labels" . | nindent 4 }}
    {{- include "entitle-agent.serviceAccountLabels" . | nindent 4 }}
  annotations:
    {{- include "entitle-agent.serviceAccountAnnotations" . | nindent 4 }}
